// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldCitites.Data;

#nullable disable

namespace WorldCitites.Migrations
{
    [DbContext(typeof(WorldCitiesContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldCitites.Models.WorldCity", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.ToTable("WorldCities", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            City = "New York",
                            Country = "USA",
                            Population = 8419600
                        },
                        new
                        {
                            CityId = 2,
                            City = "Tokyo",
                            Country = "Japan",
                            Population = 13929286
                        },
                        new
                        {
                            CityId = 3,
                            City = "London",
                            Country = "UK",
                            Population = 8982000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
